name: Typecheck, lint, and build front-end
on: [push]
jobs:
  front-end | Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        working-directory: front-end
        run: npm install
      - name: Lint
        working-directory: front-end
        run: npx eslint .
  front-end | Typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        working-directory: front-end
        run: npm install
      - name: Typecheck
        working-directory: front-end
        run: npx tsc --noEmit
    back-end | Check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Typecheck
          working-directory: back-end
          run: deno task check